<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Compile Remove="Tests/**/*.cs"/><Compile Include="../CollectionIterable.cs"/><Compile Include="../CollectionIterableAsync.cs"/><Compile Include="../CollectionIterableParallel.cs"/><Compile Include="../CollectionIterableUtils.cs"/><Compile Include="../ParallelExecutionScope.cs"/></ItemGroup></Project>